name: renovate

on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.8
        with:
          renovate-version: 35.0.0
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
